# Generated by Django 5.0 on 2025-12-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100, verbose_name='供应商名称')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='电话')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'ordering': ['-create_time'],
            },
        ),
    ]
