# Generated by Django 5.0 on 2025-12-22 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=20, unique=True, verbose_name='销售单号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额')),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实收金额')),
                ('status', models.SmallIntegerField(choices=[(0, '已创建'), (1, '已结算'), (2, '部分退货'), (3, '全部退货')], default=0, verbose_name='状态')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='收银员')),
            ],
            options={
                'verbose_name': '销售单',
                'verbose_name_plural': '销售单',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_quantity', models.IntegerField(verbose_name='销售数量')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='销售价')),
                ('return_quantity', models.IntegerField(default=0, verbose_name='退货数量')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小计')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesorder', verbose_name='销售单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '销售单明细',
                'verbose_name_plural': '销售单明细',
            },
        ),
    ]
