# Generated by Django 5.0 on 2025-12-22 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=20, unique=True, verbose_name='商品编码')),
                ('product_name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='分类')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='采购价')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='销售价')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='库存')),
                ('warning_quantity', models.IntegerField(default=10, verbose_name='预警库存')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='suppliers.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-create_time'],
            },
        ),
    ]
