# Generated by Django 5.0 on 2025-12-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(error_messages={'unique': '该商品编码已存在！请更换编码'}, max_length=20, unique=True, verbose_name='商品编码'),
        ),
    ]
